/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Fabio
 */
public class FormDieta extends javax.swing.JFrame {

    /**
     * Creates new form FormDieta
     */
    public FormDieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        javax.swing.JButton Menu = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel16.setText("g");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(314, 467, 6, 14);

        jLabel17.setText("Ingredientes");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(141, 315, 61, 14);

        jLabel5.setText("Cálcio:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(41, 245, 32, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dieta", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(64, 216, 256, 20);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 90, 31, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliete", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(64, 190, 256, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(77, 268, 33, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(64, 49, 46, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredientes" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(67, 362, 135, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(166, 268, 33, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredientes" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(67, 386, 135, 20);

        jLabel4.setText("Descrição:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 118, 50, 14);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredientes" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(67, 412, 135, 20);

        jLabel6.setText("Proieína:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(31, 271, 42, 14);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredientes" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(67, 438, 135, 20);

        jLabel8.setText("Gordura:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 271, 43, 14);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredientes" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(67, 464, 135, 20);

        jLabel11.setText("Vitaminas:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(113, 271, 49, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(64, 118, 256, 61);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 362, 90, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(220, 386, 90, 20);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(220, 412, 90, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(166, 242, 33, 20);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(220, 438, 90, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(287, 242, 33, 20);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(220, 464, 90, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText(" Calculo de Dieta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 190, 30);

        jLabel9.setText("Quant.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(257, 342, 34, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(64, 87, 256, 20);

        jLabel10.setText("g");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(314, 365, 6, 14);

        jLabel12.setText("Calorias:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 245, 42, 14);

        jLabel13.setText("g");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(314, 389, 6, 14);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(77, 242, 33, 20);

        jLabel14.setText("g");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(314, 415, 6, 14);

        jLabel7.setText("Carboidratos:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(217, 245, 66, 14);

        jLabel15.setText("g");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(314, 441, 6, 14);

        jLabel2.setText("Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 52, 14, 14);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(287, 268, 33, 20);

        jLabel18.setText("Calculo da Dieta");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(481, 52, 77, 14);

        jLabel19.setText("Nome:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(393, 78, 50, 14);

        jLabel20.setText("Idade:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(392, 93, 60, 14);

        jLabel21.setText("Sexo:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(396, 113, 50, 14);

        jLabel22.setText("Altura:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(391, 133, 60, 14);

        jLabel23.setText("Peso:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(397, 173, 50, 14);

        jLabel24.setText("Peso Ideal:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(370, 153, 80, 14);

        jLabel25.setText("Dieta:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(395, 193, 50, 14);

        jLabel26.setText("Cálcio:");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(410, 370, 60, 14);

        jLabel27.setText("Proieína:");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(400, 390, 70, 14);

        jLabel28.setText("Vitaminas:");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(390, 430, 70, 14);

        jLabel29.setText("Calorias:");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(400, 410, 70, 14);

        jLabel30.setText("Carboidratos:");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(380, 460, 90, 14);

        jLabel31.setText("Gordura:");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(400, 480, 70, 14);

        jLabel32.setText("Ingrediente:");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(364, 253, 80, 14);

        jLabel33.setText("Ingrediente:");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(364, 213, 80, 14);

        jLabel34.setText("Ingrediente:");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(364, 233, 80, 14);

        jLabel35.setText("Ingrediente:");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(364, 273, 80, 14);

        jLabel36.setText("Ingrediente:");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(364, 293, 80, 14);

        jLabel37.setText("Quant.");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(543, 213, 60, 14);

        jLabel38.setText("Quant.");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(543, 233, 60, 14);

        jLabel39.setText("Quant.");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(543, 253, 60, 14);

        jLabel40.setText("Quant.");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(543, 273, 60, 14);

        jLabel41.setText("Quant.");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(543, 293, 60, 14);

        jLabel42.setText("Quant.Exigida");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(443, 342, 90, 14);

        jLabel43.setText("Quant.Atendida");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(553, 342, 100, 14);

        jLabel44.setText("X");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(529, 342, 6, 14);

        Calcular.setText("Calcular");
        getContentPane().add(Calcular);
        Calcular.setBounds(100, 510, 71, 23);

        Limpar.setText("Limpar");
        getContentPane().add(Limpar);
        Limpar.setBounds(190, 510, 63, 23);

        Menu.setText("Menu");
        Menu.setToolTipText("");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu);
        Menu.setBounds(569, 10, 80, 23);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel45);
        jLabel45.setBounds(-210, -70, 920, 650);

        setSize(new java.awt.Dimension(694, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        TelaPrincipal form = new TelaPrincipal();
        form.setVisible(true);
        form.setSize(700,600);
        dispose();
    }//GEN-LAST:event_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDieta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Limpar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
