/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Fabio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jButtonCadDieta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonCadExigencia1 = new javax.swing.JButton();
        jButtonCadDieta1 = new javax.swing.JButton();
        jButtonFormAlimentos = new javax.swing.JButton();
        jButtonFormCliente = new javax.swing.JButton();
        jButtonFormExigencia = new javax.swing.JButton();
        jButtonFormDieta = new javax.swing.JButton();
        jLabelLogo1 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Nutripack.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCadDieta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCadDieta.setText("Cadastro Alimentos");
        jButtonCadDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadDietaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadDieta);
        jButtonCadDieta.setBounds(170, 380, 430, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Cadastro Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 460, 430, 40);

        jButtonCadExigencia1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCadExigencia1.setText("Cadastro Exigencia");
        jButtonCadExigencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadExigencia1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadExigencia1);
        jButtonCadExigencia1.setBounds(170, 500, 430, 40);

        jButtonCadDieta1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCadDieta1.setText("Cadastro Dieta");
        jButtonCadDieta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadDieta1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadDieta1);
        jButtonCadDieta1.setBounds(170, 420, 430, 40);

        jButtonFormAlimentos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonFormAlimentos.setText("Alimentos");
        jButtonFormAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormAlimentosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFormAlimentos);
        jButtonFormAlimentos.setBounds(510, 220, 180, 150);

        jButtonFormCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonFormCliente.setText("Clientes");
        jButtonFormCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFormCliente);
        jButtonFormCliente.setBounds(80, 40, 180, 160);

        jButtonFormExigencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonFormExigencia.setText("Exigencias");
        jButtonFormExigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormExigenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFormExigencia);
        jButtonFormExigencia.setBounds(510, 40, 180, 160);

        jButtonFormDieta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonFormDieta.setText("Dietas");
        jButtonFormDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormDietaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFormDieta);
        jButtonFormDieta.setBounds(80, 220, 180, 140);

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Nutripack.png"))); // NOI18N
        getContentPane().add(jLabelLogo1);
        jLabelLogo1.setBounds(250, 100, 300, 290);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-210, -60, 980, 620);

        setSize(new java.awt.Dimension(776, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadDietaActionPerformed
     CadUsuario clientes = new CadUsuario();
     clientes.setVisible(true);
     dispose();
     
    }//GEN-LAST:event_jButtonCadDietaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
CadExigencia exigencia = new CadExigencia();
     exigencia.setVisible(true);
     dispose();
         }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCadExigencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadExigencia1ActionPerformed
        CadDieta dieta = new CadDieta();
     dieta.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButtonCadExigencia1ActionPerformed

    private void jButtonCadDieta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadDieta1ActionPerformed
        CadIngrediente ingrediente = new CadIngrediente();
     ingrediente.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButtonCadDieta1ActionPerformed

    private void jButtonFormAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormAlimentosActionPerformed
       FormIngrediente formingrediente = new FormIngrediente();
     formingrediente.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButtonFormAlimentosActionPerformed

    private void jButtonFormClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormClienteActionPerformed
      FormCliente formclientes = new FormCliente();
     formclientes.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButtonFormClienteActionPerformed

    private void jButtonFormExigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormExigenciaActionPerformed
       FormExigencia formexigencia = new FormExigencia();
     formexigencia.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButtonFormExigenciaActionPerformed

    private void jButtonFormDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormDietaActionPerformed
        FormDieta dieta = new FormDieta();
     dieta.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButtonFormDietaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadDieta;
    private javax.swing.JButton jButtonCadDieta1;
    private javax.swing.JButton jButtonCadExigencia1;
    private javax.swing.JButton jButtonFormAlimentos;
    private javax.swing.JButton jButtonFormCliente;
    private javax.swing.JButton jButtonFormDieta;
    private javax.swing.JButton jButtonFormExigencia;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    // End of variables declaration//GEN-END:variables
}
